import AboutUs from "@/components/Shared/AboutUs/AboutUs";
import Footer from "@/components/Shared/Footer/Footer";
import Navbar from "@/components/Shared/Navbar/Navbar";
import getData from "@/utils/getData";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NightHawk",
  description: "Generated by create next app",
};



export default async function RootLayout({ children }) {

  const data = await getData('general/application-settings');

  console.log(data);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="sticky top-0 z-50">
          <Navbar />
        </div>
        {children}

        <AboutUs />
        <Footer />
      </body>
    </html>
  );
}
